// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhqdooqzaadgpwniyfqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocWRvb3F6YWFkZ3B3bml5ZnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODY1NjEsImV4cCI6MjA2MzU2MjU2MX0.24Wvq-6dFLIrsrFwWHswEKuBp9Tvgt6EMqC5FIJc9Lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);